# NumPy Exercises

Reference for some of these exercises is [here](https://www.w3resource.com/python-exercises/).

## Exercise 1

Write a NumPy program to create a random array with 100 real-valued elements between 1 & 5 and compute the following for this array rounded to 2 decimal places:
- average (that is, the sample mean)
- population variance and population standard deviation (default option in NumPy)
- sample variance and sample standard deviation

**Hint:** For sample variance and sample standard deviation, use the `ddof=1` parameter value.

**Explanations**

Population variance

$$\text{Population variance} = \frac{\sum_{i=1}^{N}(X_i - \bar{X})^{2}}{N}$$

Sample variance

$$\text{Sample variance} = \frac{\sum_{i=1}^{N}(X_i - \bar{X})^{2}}{N-1}$$

In [15]:
import numpy as np

sample_array = (np.random.rand(100) * 4) + 1

standard_deviation = sample_array.std(ddof=1)


1.1655840459832036


## Execise 2

Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array. 

In [18]:
def bigger_than_10(array):
    return array[array > 10]

bigger_than_10(np.array([12,34,543,2,4,23]))

array([ 12,  34, 543,  23])

## Exercise 3

Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in the first array `array1` that are not in the second one `array2`. **Hint:** This is a one-liner.

In [20]:
def set_difference(array1, array2):
    return np.setdiff1d(array1, array2)
array1 = np.array([2,3,4,5,6])
array2 = np.array([4,5,6,7,8])
set_difference(array1, array2)

array([2, 3])

## Exercise 4

Write a NumPy program to calculate element-wise round, floor, ceiling, and truncated form of an input array.

In [28]:
def round_array(array: np.array):
    return array.round()
round_array(np.array([0.43, 1.234, 5.32]))

def floor_array(array: np.array):
    return np.floor(array) // 1
floor_array(np.array([0.43, 1.234, 5.32]))

array([0., 1., 5.])

***
www.featureranking.com